### ISSUE TITLE
allow /etc/sysconfig/qat to have comment lines

### ISSUE THREAD

**Issue by mrkz** [intel/qatlib#58]
It's a common practice for configuration files in `/etc/sysconfig` to have comments in them, some examples on my current `Fedora 38` machine are:

```bash
$ cat /etc/sysconfig/firewalld
# firewalld command line args
# possible values: --debug
FIREWALLD_ARGS=
```

and

```bash
$ cat /etc/sysconfig/anaconda
# This file has been generated by the Anaconda Installer 38.23.4

[General]
post_install_tools_disabled = 0
```

however, if I use comments on `/etc/sysconfig/qat` I get failures in configuring the device.

Please allow the `/etc/sysconfig/qat` file to be able to contain comments in them and ignore lines starting with `#`

**Comment by jdschuet** [comment]
Can you confirm whether this is observed with comments as shown above?   (where comment starts at the beginning of line)
Or is this observed with comments that occur after the contents of the line.. something like:
POLICY = 1  # This is comment

**Comment by mrkz** [comment]
I had both comment patterns, but then I was contacted internally and got confirmation that comment-only lines are handled correctly, so I'd say the culprit may be the later
```sh
POLICY=1 # comment
```

**Comment by jdschuet** [comment]
Thank-you for confirming.  I've recreated the issue and also see that it affects comments at the end of line.  I've raised internal ticket to track this through resolution.   Thank-you for raising this issue.

**Comment by jdschuet** [comment]
Update with planned resolution.  Comments are supported at beginning of line, but not at end of line.
