### ISSUE TITLE
Does KTLS support offloading crypto operation to QAT device?

### ISSUE THREAD

**Issue by liverbirdkte** [intel/qatlib#68]
Hi guys, I'm looking at KTLS(https://docs.kernel.org/networking/tls-offload.html) which supports offloading crypto work to NICs. Is it possible to use QAT in this scenario, to let kernel offload crypto to QAT device? If so, do you have any performance benchmark? Thanks!

**Comment by liverbirdkte** [comment]
Hi @jdschuet @fionatrahe, it seems KTLS crypto can only be offloaded to NIC hardware, there's no way to use QAT to accelerate encryption and decryption of kernel TLS. Is my understanding right?

**Comment by gcabiddu** [comment]
Looking at the documentation and the code, it appears that kTLS can use accelerators through the Linux Crypto framework when running in Software crypto mode (TLS_SW).

**Comment by liverbirdkte** [comment]
@gcabiddu, yes, it should work to specify qat related cipher with KTLS, I'll try with this, thanks!
