### ISSUE TITLE
Run cpa_sample_code runTests=32, print `There are no compression instances`

### ISSUE THREAD

**Issue by Weifanzhao** [intel/qatlib#74]
CPU :  Intel(R) Xeon(R) Platinum 8460Y+
Linux : Fedora 37, kernel version is 6.5.12-100.fc37.x86_64

I have installed and configured as [QATlib User’s Guide](https://intel.github.io/quickassist/qatlib/index.html) step by step. As title shows :

**$ cpa_sample_code runTests=32**
qaeMemInit started
icp_sal_userStartMultiProcess("SSL") started
*** QA version information ***
device ID               = 0
software                = 23.11.0
*** END QA version information ***
There are no compression instances
Sample code completed successfully.

**$ lspci -d 8086:4940 && lspci -d 8086:4941 && lspci -d 8086:4942 && lspci -d 8086:4943**
6b:00.0 Co-processor: Intel Corporation 4xxx Series QAT (rev 40)
6b:00.1 Co-processor: Intel Corporation Device 4941 (rev 40)
6b:00.2 Co-processor: Intel Corporation Device 4941 (rev 40)
6b:00.3 Co-processor: Intel Corporation Device 4941 (rev 40)
6b:00.4 Co-processor: Intel Corporation Device 4941 (rev 40)
6b:00.5 Co-processor: Intel Corporation Device 4941 (rev 40)
6b:00.6 Co-processor: Intel Corporation Device 4941 (rev 40)
6b:00.7 Co-processor: Intel Corporation Device 4941 (rev 40)
6b:01.0 Co-processor: Intel Corporation Device 4941 (rev 40)
6b:01.1 Co-processor: Intel Corporation Device 4941 (rev 40)
6b:01.2 Co-processor: Intel Corporation Device 4941 (rev 40)
6b:01.3 Co-processor: Intel Corporation Device 4941 (rev 40)
6b:01.4 Co-processor: Intel Corporation Device 4941 (rev 40)
6b:01.5 Co-processor: Intel Corporation Device 4941 (rev 40)
6b:01.6 Co-processor: Intel Corporation Device 4941 (rev 40)
6b:01.7 Co-processor: Intel Corporation Device 4941 (rev 40)
6b:02.0 Co-processor: Intel Corporation Device 4941 (rev 40)

**$ lsmod | grep qat**
qat_4xxx               24576  0
intel_qat             299008  1 qat_4xxx
crc8                   12288  1 intel_qat

**Comment by gcabiddu** [comment]
From the log above I see that in your setup you have a single device. That is configured for crypto.
You can configure your device for compression by adding the string `ServicesEnabled=dc` to the file /etc/sysconfig/qat and restarting the service, `systemctl restart qat`. See https://github.com/intel/qatlib/blob/ec817626e7de237b24cfb91b7cad076902df603a/INSTALL#L409
