### ISSUE TITLE
Does qatlib support epoll?

### ISSUE THREAD

**Issue by neel-patel-1** [intel/qatlib#76]
How should one enable epoll with the new configuration file format? 

With QAT 2.0, it appears we can enable using:  "IsPolled = 2".

Is there an equivalent option in the new config file format? Is there a way to toggle use of the old config format to specify parameters from the old config file?

**Comment by gcabiddu** [comment]
Hi @neel-patel-1, qatlib does not support yet epoll.

**Comment by neel-patel-1** [comment]
Hi @gcabiddu . Thanks for letting me know. Feel free to mark as resolved.
