### ISSUE TITLE
[Question] Enable both Userspace and Kernelspace usage of QAT

### ISSUE THREAD

**Issue by AsaMyth** [intel/qatlib#81]
Per my understanding, qatlib enables the userspace usage with QAT VF bound to vfio-pci.
Seeing from in-tree driver, QAT can also be used in kernel-space.

https://github.com/torvalds/linux/blob/dccb07f2914cdab2ac3a5b6c98406f765acab803/drivers/crypto/intel/qat/qat_common/qat_comp_algs.c#L319

Q: does the kernel-space usage only work with SRIOV disabled? If not, how to do the setup to share a QAT device for user-space and kernl space usage?

**Comment by gcabiddu** [comment]
> Q: does the kernel-space usage only work with SRIOV disabled?

Correct. Offload from kernel space works only if the PF driver is loaded and bounded to the PF. There is no VF driver for QAT4xxx.
